### ISSUE TITLE
verify-metadata-generator not installed?

### ISSUE THREAD

**Issue by galund** [alphagov/verify-local-startup#64]
Looks like there is now a dependency on verify-metadata-generator, but I don't have this installed yet and it's not getting installed automatically. May well be PBKAC.

```
|  _ \ _ __ ___ _ __   |  _ \  _____   __ |  _ \| |/ /_ _|
| |_) | '__/ _ \ '_ \  | | | |/ _ \ \ / / | |_) | ' / | | 
|  __/| | |  __/ |_) | | |_| |  __/\ V /  |  __/| . \ | | 
|_|   |_|  \___| .__/  |____/ \___| \_/   |_|   |_|\_\___|
               |_|                                        
Generating Root CA: verify
	Generating Intermediate CA: hub
		Generating cert: hub_signing_primary
		Generating cert: hub_encryption_primary
		Generating cert: hub_signing_secondary
		Generating cert: hub_encryption_secondary
	Generating Intermediate CA: idp
		Generating cert: stub_idp_signing_primary
		Generating cert: stub_idp_signing_secondary
	Generating Intermediate CA: rp
		Generating cert: sample_rp_signing_primary
		Generating cert: sample_rp_encryption_primary
		Generating cert: sample_rp_signing_secondary
		Generating cert: sample_rp_encryption_secondary
		Generating cert: sample_rp_msa_signing_primary
		Generating cert: sample_rp_msa_encryption_primary
		Generating cert: sample_rp_msa_signing_secondary
		Generating cert: sample_rp_msa_encryption_secondary
	Generating Intermediate CA: metadata
		Generating cert: metadata_signing_a
		Generating cert: metadata_signing_b
Adding certificate verify-root to hub truststore
Certificate was added to keystore
Adding certificate verify-hub to hub truststore
Certificate was added to keystore
Adding certificate verify-idp to hub truststore
Certificate was added to keystore
Adding certificate verify-root to hub_federation truststore
Certificate was added to keystore
Adding certificate verify-hub to hub_federation truststore
Certificate was added to keystore
Adding certificate verify-root to idp_federation truststore
Certificate was added to keystore
Adding certificate verify-idp to idp_federation truststore
Certificate was added to keystore
Adding certificate verify-root to relying_parties truststore
Certificate was added to keystore
Adding certificate verify-rp to relying_parties truststore
Certificate was added to keystore
Adding certificate verify-root to metadata truststore
Certificate was added to keystore
Adding certificate verify-metadata to metadata truststore
Certificate was added to keystore
Generating metadata sources
Generating metadata XML
Signing metadata
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/shibboleth/tool/xmlsectool/XMLSecTool has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
cp: can't stat 'metadata/output/dev/metadata.signed.xml': No such file or directory
Signing metadata
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/shibboleth/tool/xmlsectool/XMLSecTool has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
cp: can't stat 'metadata/output/compliance-tool/metadata.signed.xml': No such file or directory
Generating compatible federation config
https://github.com/alphagov/verify-metadata-generator.git (at master@7990ab9) is not yet checked out.
Run `bundle install` first.
```

**Comment by j-maynard** [comment]
@galund This actually looks to be an issue with `xmlsectool`... There have been a number of updates to `xmlsectool`.  One of the most recent seems to have change the minimum java version from 8 to 11 which seems to have cause a few issues.  We pushed out a fix to this today which fixes your issue.

Please do a pull on the master branch of `verify-local-startup` and confirm that you don't still encounter the issue.  Another test is to do a fresh clone in to an empty directory and confirm that works.  Once you've confirm it works I shall close this issue.

**Comment by j-maynard** [comment]
I should add... There is probably a bug here which should stop the scripts from executing if there is an issue at any point during the metadata generation process.  The failure to run `xmlsectool` I think meant that a later step in the script which checkouts `verify-metadata-generator` probably via `bundle` or `bundle install` failed to run.

**Comment by j-maynard** [comment]
Caught up with @galund who confirmed he was able to get this working.  Closing this issue.
